// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtQEZOlPKpaUX0cO6MIFVd8zTiBBm9mUI',
    appId: '1:220032001055:web:fb81369639556fd72ea12a',
    messagingSenderId: '220032001055',
    projectId: 'edens-b484a',
    authDomain: 'edens-b484a.firebaseapp.com',
    storageBucket: 'edens-b484a.appspot.com',
    measurementId: 'G-37ET9XSJLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2hbCVzvenBtbq88xZGiBRwOt354EW1-w',
    appId: '1:220032001055:android:3995723b1a18ce8f2ea12a',
    messagingSenderId: '220032001055',
    projectId: 'edens-b484a',
    storageBucket: 'edens-b484a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxKfTLktHvumkHELcn33PripaLzKcJLQ4',
    appId: '1:220032001055:ios:4e66a52b4bf7182f2ea12a',
    messagingSenderId: '220032001055',
    projectId: 'edens-b484a',
    storageBucket: 'edens-b484a.appspot.com',
    iosBundleId: 'com.example.edens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxKfTLktHvumkHELcn33PripaLzKcJLQ4',
    appId: '1:220032001055:ios:893b938274191f6d2ea12a',
    messagingSenderId: '220032001055',
    projectId: 'edens-b484a',
    storageBucket: 'edens-b484a.appspot.com',
    iosBundleId: 'com.example.edens.RunnerTests',
  );
}
